/* Auto-generated by cbindgen — do not edit manually */
#ifndef WHATSAPP_BRIDGE_H
#define WHATSAPP_BRIDGE_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Error codes ─────────────────────────────────────────────────────────── */

#define WA_OK                 0
#define WA_ERR_NULL_POINTER  -1
#define WA_ERR_BAD_KEY_LEN   -2
#define WA_ERR_BAD_IV_LEN    -3
#define WA_ERR_ENCRYPT_FAIL  -4
#define WA_ERR_DECRYPT_FAIL  -5
#define WA_ERR_OUTPUT_SMALL  -6
#define WA_ERR_HKDF_FAIL     -7
#define WA_ERR_RNG_FAIL      -8

/* ── Crypto ───────────────────────────────────────────────────────────────── */

/**
 * Compute MD5 hash.
 * @param data       input bytes
 * @param data_len   length of input
 * @param out_buf    output buffer, must be >= 16 bytes
 * @param out_len    [in] capacity, [out] bytes written (always 16)
 * @return WA_OK or negative error code
 */
int32_t wa_md5(
    const uint8_t *data, size_t data_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * Compute SHA-256 hash.
 * @param out_buf    must be >= 32 bytes; *out_len set to 32
 */
int32_t wa_sha256(
    const uint8_t *data, size_t data_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * Compute HMAC-SHA256.
 * @param out_buf    must be >= 32 bytes; *out_len set to 32
 */
int32_t wa_hmac_sha256(
    const uint8_t *data, size_t data_len,
    const uint8_t *key,  size_t key_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * HKDF-SHA256 expand.
 * @param salt / salt_len   may be NULL/0 (no salt)
 * @param info / info_len   may be NULL/0 (empty info)
 * @param out_buf           output buffer of out_len bytes
 * @param out_len           desired output length (unchanged on success)
 */
int32_t wa_hkdf(
    const uint8_t *ikm,  size_t ikm_len,
    const uint8_t *salt, size_t salt_len,
    const uint8_t *info, size_t info_len,
    uint8_t *out_buf, size_t out_len);

/**
 * AES-256-GCM encrypt. Auth tag (16 bytes) appended to ciphertext.
 * @param key        32 bytes
 * @param iv         12 bytes
 * @param aad/aad_len  may be NULL/0
 * @param out_buf    must be >= plaintext_len + 16; *out_len set to actual size
 */
int32_t wa_aes_encrypt_gcm(
    const uint8_t *plaintext, size_t plaintext_len,
    const uint8_t *key,
    const uint8_t *iv,
    const uint8_t *aad, size_t aad_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-GCM decrypt. Expects auth tag (16 bytes) appended to ciphertext.
 */
int32_t wa_aes_decrypt_gcm(
    const uint8_t *ciphertext, size_t ciphertext_len,
    const uint8_t *key,
    const uint8_t *iv,
    const uint8_t *aad, size_t aad_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-CBC encrypt with random IV. IV prepended to output.
 * @param key        32 bytes
 * @param out_buf    must be >= plaintext_len + 32 (IV + padding headroom)
 */
int32_t wa_aes_encrypt_cbc(
    const uint8_t *plaintext, size_t plaintext_len,
    const uint8_t *key,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-CBC decrypt. First 16 bytes of ciphertext are the IV.
 */
int32_t wa_aes_decrypt_cbc(
    const uint8_t *ciphertext, size_t ciphertext_len,
    const uint8_t *key,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-CBC encrypt with explicit IV (no IV prefix in output).
 * @param iv  16 bytes
 */
int32_t wa_aes_encrypt_cbc_iv(
    const uint8_t *plaintext, size_t plaintext_len,
    const uint8_t *key,
    const uint8_t *iv,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-CBC decrypt with explicit IV.
 */
int32_t wa_aes_decrypt_cbc_iv(
    const uint8_t *ciphertext, size_t ciphertext_len,
    const uint8_t *key,
    const uint8_t *iv,
    uint8_t *out_buf, size_t *out_len);

/**
 * AES-256-CTR encrypt/decrypt (symmetric).
 * @param key  32 bytes, iv  16 bytes
 * @param out_buf  must be >= data_len
 */
int32_t wa_aes_ctr(
    const uint8_t *data, size_t data_len,
    const uint8_t *key,
    const uint8_t *iv,
    uint8_t *out_buf, size_t *out_len);

/* ── Curve25519 ───────────────────────────────────────────────────────────── */

/**
 * Generate a Curve25519 key pair.
 * @param pub_key_out   33 bytes (0x05 prefix + 32 bytes)
 * @param priv_key_out  32 bytes
 */
int32_t wa_generate_key_pair(
    uint8_t *pub_key_out,
    uint8_t *priv_key_out);

/**
 * Diffie-Hellman shared secret.
 * @param pub_key      32 or 33 bytes (optional 0x05 prefix)
 * @param priv_key     32 bytes
 * @param out          32 bytes output
 */
int32_t wa_calculate_agreement(
    const uint8_t *pub_key, size_t pub_key_len,
    const uint8_t *priv_key,
    uint8_t *out);

/**
 * Sign a message with Ed25519-flavored Curve25519.
 * @param priv_key   32 bytes
 * @param out        64 bytes
 */
int32_t wa_calculate_signature(
    const uint8_t *priv_key,
    const uint8_t *message, size_t message_len,
    uint8_t *out);

/**
 * Verify a signature.
 * @param pub_key    32 or 33 bytes
 * @param signature  64 bytes
 * @return 1 = valid, 0 = invalid, negative = error
 */
int32_t wa_verify_signature(
    const uint8_t *pub_key, size_t pub_key_len,
    const uint8_t *message, size_t message_len,
    const uint8_t *signature);

/**
 * Derive public key from private key.
 * @param priv_key  32 bytes
 * @param out       33 bytes (0x05 + 32)
 */
int32_t wa_get_public_from_private(
    const uint8_t *priv_key,
    uint8_t *out);

/* ── Key Helper ───────────────────────────────────────────────────────────── */

/**
 * Generate a random 14-bit registration ID.
 * @param out_id  receives the ID (0..16383)
 */
int32_t wa_generate_registration_id(uint32_t *out_id);

/**
 * Generate a pre-key pair.
 * @param key_id        desired key ID
 * @param pub_key_out   33 bytes
 * @param priv_key_out  32 bytes
 * @param key_id_out    echoes key_id back
 */
int32_t wa_generate_pre_key(
    uint32_t key_id,
    uint8_t *pub_key_out,
    uint8_t *priv_key_out,
    uint32_t *key_id_out);

/**
 * Generate a signed pre-key.
 * @param identity_priv_key  32-byte identity private key
 * @param signed_key_id      desired key ID
 * @param pub_key_out        33 bytes
 * @param priv_key_out       32 bytes
 * @param signature_out      64 bytes
 * @param key_id_out         echoes signed_key_id back
 */
int32_t wa_generate_signed_pre_key(
    const uint8_t *identity_priv_key,
    uint32_t signed_key_id,
    uint8_t *pub_key_out,
    uint8_t *priv_key_out,
    uint8_t *signature_out,
    uint32_t *key_id_out);

/* ── Binary Node ──────────────────────────────────────────────────────────── */

/**
 * Encode a BinaryNode (JSON) into WhatsApp binary wire format.
 *
 * JSON schema:
 *   { "tag": "...", "attrs": { "k": "v" },
 *     "content": "text" | [nodes] | { "b64": "<base64 bytes>" } }
 *
 * @param json_in / json_len  UTF-8 JSON input
 * @param out_buf / out_len   output buffer; *out_len set to actual size
 */
int32_t wa_encode_node(
    const uint8_t *json_in, size_t json_len,
    uint8_t *out_buf, size_t *out_len);

/**
 * Decode WhatsApp binary frame bytes into a BinaryNode (JSON).
 * Same JSON schema as wa_encode_node.
 */
int32_t wa_decode_node(
    const uint8_t *data, size_t data_len,
    uint8_t *out_buf, size_t *out_len);

/* ── VoIP: MLow audio codec ──────────────────────────────────────────────────
 *
 * Stateful: create a handle with *_new, drive it, free with *_free. The
 * encode/decode calls use the out_buf/out_len convention — pass a NULL or
 * too-small buffer to query the required length, then call again.
 */

typedef struct MlowEncoder MlowEncoder;
typedef struct MlowDecoder MlowDecoder;

/* Allocate / free / reset an MLow encoder. */
MlowEncoder *wa_mlow_encoder_new(void);
void wa_mlow_encoder_free(MlowEncoder *enc);
void wa_mlow_encoder_reset(MlowEncoder *enc);

/* Encode PCM (pcm/pcm_len f32 samples) into out_buf (*out_len in BYTES). */
int32_t wa_mlow_encode(
    MlowEncoder *enc,
    const float *pcm, size_t pcm_len,
    uint8_t *out_buf, size_t *out_len);

/* Allocate / free / reset an MLow decoder. */
MlowDecoder *wa_mlow_decoder_new(void);
void wa_mlow_decoder_free(MlowDecoder *dec);
void wa_mlow_decoder_reset(MlowDecoder *dec);
void wa_mlow_decoder_set_redundancy(MlowDecoder *dec, int32_t n);

/* Decode an MLow payload into out_buf (*out_len in FLOAT ELEMENTS). */
int32_t wa_mlow_decode(
    MlowDecoder *dec,
    const uint8_t *payload, size_t payload_len,
    float *out_buf, size_t *out_len);

/* ── VoIP: E2E SRTP media pipeline ────────────────────────────────────────────
 *
 * Stateful per call. lids are UTF-8 (ptr+len, not NUL-terminated). protect/
 * unprotect use the out_buf/out_len (bytes) convention. unprotect returns
 * WA_ERR_DECRYPT_FAIL with *out_len=0 when the packet is not decryptable audio.
 */

typedef struct MediaPipeline MediaPipeline;

/* Create / free a pipeline. new() returns NULL on bad UTF-8 or short callKey. */
MediaPipeline *wa_media_pipeline_new(
    const uint8_t *call_key, size_t call_key_len,
    const uint8_t *self_lid, size_t self_lid_len,
    const uint8_t *peer_lid, size_t peer_lid_len,
    uint32_t ssrc, uint32_t samples_per_packet, size_t warp_mi_tag_len);
void wa_media_pipeline_free(MediaPipeline *mp);

/* Encrypt audio payload into an SRTP packet. */
int32_t wa_media_pipeline_protect(
    MediaPipeline *mp,
    const uint8_t *payload, size_t payload_len,
    uint8_t *out_buf, size_t *out_len);

/* Decrypt an SRTP packet into its audio payload. */
int32_t wa_media_pipeline_unprotect(
    MediaPipeline *mp,
    const uint8_t *packet, size_t packet_len,
    uint8_t *out_buf, size_t *out_len);

/* Re-derive receive keys after the peer answers. 1=ok, 0=no-op, <0=error. */
int32_t wa_media_pipeline_rekey_recv(
    MediaPipeline *mp,
    const uint8_t *call_key, size_t call_key_len,
    const uint8_t *answering_peer_lid, size_t answering_peer_lid_len);

/* ── VoIP: sans-io CallEngine (signaling + media driver) ──────────────────────
 *
 * Drive loop: feed inputs (wa_call_engine_handle_*), then drain
 * wa_call_engine_poll_output until it returns 0 (TIMEOUT = drained), fetching
 * each output's payload with the matching take/last/event call. Arm timers off
 * wa_call_engine_poll_timeout. All times are monotonic milliseconds.
 *
 * Output kinds: 0=Timeout(drained) 1=Transmit 2=Playout 3=Event.
 * Event kinds:  0=RelayAllocated 1=ForeignAudio 2=RelayAllocateFailed 3=RelayAllocateTimedOut.
 */

typedef struct WaCallEngine WaCallEngine;

/* Create from a UTF-8 JSON config (callId, direction "incoming"|"outgoing",
 * selfLid, peerLid, callKey[], ssrc, samplesPerPacket, relayToken[], relayIp,
 * relayPort, integrityKey[], warpMiTagLen, enableMedia, enableSframe — snake_case).
 * Returns NULL on parse error / short callKey / bad endpoint. */
WaCallEngine *wa_call_engine_new(const uint8_t *config_json, size_t config_json_len);
void wa_call_engine_free(WaCallEngine *eng);

void wa_call_engine_start(WaCallEngine *eng, uint64_t now);
void wa_call_engine_handle_relay_packet(
    WaCallEngine *eng, uint64_t now, const uint8_t *packet, size_t packet_len);
void wa_call_engine_handle_mic_frame(
    WaCallEngine *eng, uint64_t now, const int16_t *pcm, size_t pcm_len);
void wa_call_engine_handle_timeout(WaCallEngine *eng, uint64_t now);

/* Drain one output; returns its kind. Fetch payload via the matching call. */
int32_t wa_call_engine_poll_output(WaCallEngine *eng);
int32_t wa_call_engine_take_transmit(WaCallEngine *eng, uint8_t *out_buf, size_t *out_len);
int32_t wa_call_engine_take_playout(WaCallEngine *eng, int16_t *out_buf, size_t *out_len);
int64_t wa_call_engine_last_timeout(WaCallEngine *eng);
int32_t wa_call_engine_event_kind(WaCallEngine *eng);
int32_t wa_call_engine_take_foreign_audio(WaCallEngine *eng, uint8_t *out_buf, size_t *out_len);
int32_t wa_call_engine_event_code(WaCallEngine *eng);

int64_t wa_call_engine_poll_timeout(WaCallEngine *eng);
int32_t wa_call_engine_rekey_recv(
    WaCallEngine *eng, const uint8_t *answering_peer_lid, size_t answering_peer_lid_len);
int32_t wa_call_engine_call_id(WaCallEngine *eng, uint8_t *out_buf, size_t *out_len);
int32_t wa_call_engine_direction(WaCallEngine *eng);     /* 0=out 1=in -1=unknown */
int32_t wa_call_engine_is_allocated(WaCallEngine *eng);  /* 1/0 */
int32_t wa_call_engine_is_terminated(WaCallEngine *eng); /* 1/0 */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WHATSAPP_BRIDGE_H */
